version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry for updates every weekday
    schedule:
      interval: "daily"
    ignore: # Everything not annotated here is documented in tools/update-dependencies.js
      # aws-sdk upgrades too often, do this manually
      - dependency-name: aws-sdk
      - dependency-name: commander
      - dependency-name: cross-zip
        versions: ['4.x']
      - dependency-name: html-webpack-plugin
        versions: ['5.x']
      - dependency-name: open
      - dependency-name: typescript
        versions: ['4.1.x', '4.2.x']
      - dependency-name: webpack
        versions: ['5.x']
  - package-ecosystem: "npm"
    directory: "/packages/template/typescript/tmpl"
    # Check the npm registry for updates every weekday
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/template/typescript-webpack/tmpl"
    # Check the npm registry for updates every weekday
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/template/webpack/tmpl"
    # Check the npm registry for updates every weekday
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
