version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry for updates every weekday
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: aws-sdk
      - dependency-name: webpack
        versions: ['5.x']
  - package-ecosystem: "npm"
    directory: "/packages/template/typescript/tmpl"
    # Check the npm registry for updates every weekday
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/template/typescript-webpack/tmpl"
    # Check the npm registry for updates every weekday
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/template/webpack/tmpl"
    # Check the npm registry for updates every weekday
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
