platform:
- x64
environment:
  nodejs_version: "8"
  matrix:
  - node_installer: yarn
cache:
- 'node_modules'
- '%USERPROFILE%\.electron'
branches:
  only:
  - master
  - node-8

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- npm i -g bolt@0.21.2
- if not exist "node_modules" mkdir node_modules
- ps: Remove-Item node_modules -Recurse -Force
- bolt
- yarn build
- ps: |
    $wixToolsetBinPath = ";C:\Program Files (x86)\WiX Toolset v3.11\bin;"
    $env:PATH = $env:PATH + $wixToolsetBinPath
    [Environment]::SetEnvironmentVariable("Path", $env:PATH, [EnvironmentVariableTarget]::Machine)
    if ((Get-Command "light.exe" -ErrorAction SilentlyContinue) -eq $null)
    {
      Write-Host "Unable to find light.exe in your PATH"
    }

test_script:
- node --version
- yarn --version
- yarn lint
- yarn test

build: off
